Defensive macro quoting?                                                                        
                                                                                                
I have often thought it is better to use the macro quoting functions instead of                 
the equivalent non-quoting macro macro functions.                                               
                                                                                                
* suppose I have this macro variable and I am not sure what separator the userwill use,         
* % & % * ...                                                                                   
                                                                                                
%let yrs=%str(2011,2019);                                                                       
                                                                                                
and I want to create table class20112019;                                                       
                                                                                                
data class20112019;                                                                             
   set sashelp.class;                                                                           
run;quit;                                                                                       
                                                                                                
%let cutyrs=%qsysfunc(compress(&yrs,%str(,)));                                                  
                                                                                                
%put &=cutyrs;                                                                                  
                                                                                                
data class&cutyrs;                                                                              
   set sashelp.class;                                                                           
run;quit;                                                                                       
                                                                                                
* __       _ _                                                                                  
 / _| __ _(_) |___                                                                              
| |_ / _` | | / __|                                                                             
|  _| (_| | | \__ \                                                                             
|_|  \__,_|_|_|___/                                                                             
                                                                                                
;                                                                                               
                                                                                                
NOTE: Line generated by the macro variable "CUTYRS".                                            
36     class20112019                                                                            
            --------                                                                            
            200                                                                                 
ERROR 200-322: The symbol is not recognized and will be ignored.                                
                                                                                                
37       set sashelp.class;                                                                     
38    run;                                                                                      
                                                                                                
NOTE: The SAS System stopped processing this step because of errors.                            
                                                                                                
*_           _     _   _     _                          _                                       
| |__  _   _| |_  | |_| |__ (_)___  __      _____  _ __| | _____                                
| '_ \| | | | __| | __| '_ \| / __| \ \ /\ / / _ \| '__| |/ / __|                               
| |_) | |_| | |_  | |_| | | | \__ \  \ V  V / (_) | |  |   <\__ \                               
|_.__/ \__,_|\__|  \__|_| |_|_|___/   \_/\_/ \___/|_|  |_|\_\___/                               
                                                                                                
;                                                                                               
                                                                                                
data class%unquote(&cutyrs);                                                                    
   set sashelp.class;                                                                           
run;quit;                                                                                       
                                                                                                
*___                   __             _   _     _                                               
|_ _|  _ __  _ __ ___ / _| ___ _ __  | |_| |__ (_)___                                           
 | |  | '_ \| '__/ _ \ |_ / _ \ '__| | __| '_ \| / __|                                          
 | |  | |_) | | |  __/  _|  __/ |    | |_| | | | \__ \                                          
|___| | .__/|_|  \___|_|  \___|_|     \__|_| |_|_|___/                                          
      |_|                                                                                       
                                                                                                
I think in handles more separators.                                                             
                                                                                                
                                                                                                
%let yrs='2011,2019';                                                                           
                                                                                                
%let yrs=%sysfunc(compress(&yrs,%str(,)));                                                      
                                                                                                
%put &=yrs;                                                                                     
                                                                                                
data class%sysfunc(dequote(&yrs));                                                              
   set sashelp.class;                                                                           
run;quit;                                                                                       
                                                                                                
*                      _                                                                        
 _ __ ___   __ _ _   _| |__   ___                                                               
| '_ ` _ \ / _` | | | | '_ \ / _ \                                                              
| | | | | | (_| | |_| | |_) |  __/                                                              
|_| |_| |_|\__,_|\__, |_.__/ \___|                                                              
                 |___/                                                                          
;                                                                                               
                                                                                                
%symdel cut / nowarn;                                                                           
                                                                                                
%let yrs='2011,2019';                                                                           
                                                                                                
%dosubl(%nrstr(                                                                                 
  data _null_;                                                                                  
     call symputx('cut',compress(&yrs,"',"));                                                   
  run;quit;                                                                                     
  ));                                                                                           
                                                                                                
%put &=cut;                                                                                     
                                                                                                
                                                                                                
data class&cut;                                                                                 
   set sashelp.class;                                                                           
run;quit;                                                                                       
                                                                                                
                                                                                                
